format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$username\
[](fg:#769ff0 bg:#0312A0)\
$directory\
[](fg:#0312A0 bg:#4F5B82)\
$git_branch\
$git_status\
[ ](fg:#4F5B82)\
$character"""

[username]
format = "[ $user](fg:#e3e5e5 bg:#769ff0)"
disabled = false
show_always = true

[directory]
style = "fg:#a0a9cb bg:#0312A0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#4F5B82)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#4F5B82)]($style)'

# [character] # 設定対象のモジュール名は 'character'
# success_symbol = ''
