format = """
${custom.os_logo}\
$directory\
${custom.git_symbol}\
${custom.git_repo}\
$git_branch\
$git_status\
\n
$character\
"""

right_format = """
"""

# palette = "catppuccin_mocha"
palette = "everforest_dark_soft"

[palettes.everforest_dark_soft]
background = "#333c43"
text-black = "#181926"
text-white = "#cad3f5"
logo = "#a7c080"
directory = "#7fbbb3"
repo = "#d3c6aa"
git = "#d699b6"

fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"
bg_dim = "#293136"
bg0 = "#333c43"
bg1 = "#3a464c"
bg2 = "#434f55"
bg3 = "#4d5960"
bg4 = "#555f66"
bg5 = "#5d6b66"
bg_visual = "#5c3f4f"
bg_red = "#59464c"
bg_green = "#48584e"
bg_blue = "#3f5865"
bg_yellow = "#55544a"

[palettes.catppuccin_mocha]
background = "#1e1e2e"
text-black = "#181926"
text-white = "#cad3f5"
logo = "#a6da95"
directory = "#8bd5ca"
repo = "#8aadf4"
git = "#c6a0f6"

rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[custom.os_logo]
command = """
if grep -qi 'ubuntu' /etc/os-release; then
  echo ""  # Ubuntu
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo ""  # Linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo ""  # macOS
else
  echo "?"  # 不明なOS
fi
"""
when = "true"
style = "logo"
format = "[](fg:$style)[ $output ](fg:text-black bg:$style bold)[](fg:$style)"

# [username]
# format = "[](fg:background bg:bright-cyan)[ $user ](fg:gray5 bg:bright-cyan)[](bright-cyan)"
# disabled = false
# show_always = true

[directory]
truncation_length = 0
truncate_to_repo = false
style = "directory"
format = "[](fg:$style)[ $path ](fg:text-black bg:$style)[](fg:$style)"

[custom.git_symbol]
when = true
require_repo = true
command='echo ""'
style = "repo"
format = "[](fg:$style)[ $output](fg:text-black bg:$style bold)"

[custom.git_repo]
when = true
require_repo = true
command='git rev-parse --show-toplevel | sed -e "s,$(ghq root)/github\.com/,,g" -e "s,$(ghq root)/,,"'
style = "repo"
format = "[ $output ](fg:text-black bg:$style bold)[](fg:$style bg:background)"

[git_branch]
symbol = ""
style = "git"
format = "[](fg:background bg:$style)[[ $symbol $branch ](fg:text-black bg:$style)](fg:char bg:$style)"

[git_status]
style = "git"
format = "[[($all_status $ahead_behind) ](fg:text-black bg:$style)]()[](fg:$style)"

[character]
# success_symbol = '[](fg:green bold)'
# error_symbol = '[](fg:red bold)'

