format = """
${custom.os_logo}\
$directory\
${custom.git_symbol}\
${custom.git_repo}\
$git_branch\
$git_status\
\n
$character\
"""

right_format = """
"""

palette = "everforest"

[palettes.everforest]
background = "#343F44"

green = "#abbf86"
bright-green = "#90a030"

yellow = "#d5bd86"
bright-yellow = "#d5a236"

cyan = "#90be95"
bright-cyan = "#58a47e"

blue = "#8cb9b2"
bright-blue = "#5392c0"

gray1 = "#FFFFFF"
gray2 = "#D9D9D9"
gray3 = "#969696"
gray4 = "#525252"
gray5 = "#000000"

# palette = "colors"
#
# [palettes.colors]
# background = "#24292d"
#
# yellow1 = "#F0F4C3"
# yellow2 = "#DCE775"
# yellow3 = "#CDDC39"
# yellow4 = "#AFB42B"
# yellow5 = "#827717"
#
# green1 = "#DCEDC8"
# green2 = "#AED581"
# green3 = "#8BC34A"
# green4 = "#689F38"
# green5 = "#33691E"
#
# gray1 = "#FFFFFF"
# gray2 = "#D9D9D9"
# gray3 = "#969696"
# gray4 = "#525252"
# gray5 = "#000000"

[custom.os_logo]
command = """
if grep -qi 'ubuntu' /etc/os-release; then
  echo ""  # Ubuntu
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  echo ""  # Linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo ""  # macOS
else
  echo "?"  # 不明なOS
fi
"""
when = "true"
style = "blue"
format = "[](fg:background bg:$style)[ $output ](fg:gray4 bg:$style bold)[](fg:$style bg:background)"

# [username]
# format = "[](fg:background bg:bright-cyan)[ $user ](fg:gray5 bg:bright-cyan)[](bright-cyan)"
# disabled = false
# show_always = true

[directory]
truncation_length = 0
truncate_to_repo = false
style = "cyan"
format = "[](fg:background bg:$style)[ $path ](fg:gray5 bg:$style)[](fg:$style bg:background)"

[custom.git_symbol]
when = true
require_repo = true
command='echo ""'
style = "green"
format = "[](fg:background bg:$style)[ $output](fg:gray4 bg:$style bold)"

[custom.git_repo]
when = true
require_repo = true
command='git rev-parse --show-toplevel | sed -e "s,$(ghq root)/github\.com/,,g" -e "s,$(ghq root)/,,"'
style = "green"
format = "[ $output ](fg:gray4 bg:$style bold)[](fg:$style bg:background)"

[git_branch]
symbol = ""
style = "yellow"
format = "[](fg:background bg:$style)[[ $symbol $branch ](fg:gray5 bg:$style)](fg:char bg:$style)"

[git_status]
style = "yellow"
format = "[[($all_status $ahead_behind) ](fg:gray5 bg:$style)]()[](fg:$style bg:background)"

[character]
# success_symbol = '[](fg:green bold)'
# error_symbol = '[](fg:red bold)'

