#!/usr/bin/env bash

code --install-extension aaron-bond.better-comments --force
code --install-extension asvetliakov.vscode-neovim --force
code --install-extension bierner.markdown-preview-github-styles --force
code --install-extension bradlc.vscode-tailwindcss --force
code --install-extension christian-kohler.path-intellisense --force
code --install-extension dbaeumer.vscode-eslint --force
code --install-extension dsznajder.es7-react-js-snippets --force
code --install-extension eamodio.gitlens --force
code --install-extension esbenp.prettier-vscode --force
code --install-extension formulahendry.auto-rename-tag --force
code --install-extension github.copilot --force
code --install-extension github.copilot-chat --force
code --install-extension golang.go --force
code --install-extension humao.rest-client --force
code --install-extension jmaxwilson.vscode-povray --force
code --install-extension mechatroner.rainbow-csv --force
code --install-extension mintlify.document --force
code --install-extension mosapride.zenkaku --force
code --install-extension ms-azuretools.vscode-docker --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-toolsai.jupyter --force
code --install-extension ms-toolsai.jupyter-keymap --force
code --install-extension ms-toolsai.jupyter-renderers --force
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force
code --install-extension ms-vscode-remote.remote-containers --force
code --install-extension ms-vscode.cmake-tools --force
code --install-extension ms-vscode.cpptools --force
code --install-extension ms-vscode.cpptools-extension-pack --force
code --install-extension ms-vscode.cpptools-themes --force
code --install-extension ms-vscode.vscode-typescript-next --force
code --install-extension ms-vsliveshare.vsliveshare --force
code --install-extension naumovs.color-highlight --force
code --install-extension oderwat.indent-rainbow --force
code --install-extension phind.phind --force
code --install-extension pkief.material-icon-theme --force
code --install-extension prisma.prisma --force
code --install-extension redhat.vscode-yaml --force
code --install-extension shardulm94.trailing-spaces --force
code --install-extension streetsidesoftware.code-spell-checker --force
code --install-extension tamasfe.even-better-toml --force
code --install-extension twxs.cmake --force
code --install-extension usernamehw.errorlens --force
code --install-extension visualstudioexptteam.intellicode-api-usage-examples --force
code --install-extension visualstudioexptteam.vscodeintellicode --force
code --install-extension webdevsnyc.aws-sam-snippets --force
code --install-extension yzhang.markdown-all-in-one --force
