# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

imports:
  - "./60QA.yml"
  - "./paper.yml"

matches:
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: ";lip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "ipconfig getifaddr en0"

  - trigger: ";gip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
